import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/layout/Navbar";
import Main from "./Main";
import Footer from "@/components/layout/Footer";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});
const lemon = localFont({
	src: "./fonts/Lemon.woff",
	variable: "--font-lemon",
});
const lexend = localFont({
	src: "./fonts/Lexend.woff",
	variable: "--font-lexend",
});
const lexendDeca = localFont({
	src: "./fonts/Lexend_Deca.woff",
	variable: "--font-lexend-deca",
});
const lexendExa = localFont({
	src: "./fonts/Lexend_Exa.woff",
	variable: "--font-lexend-exa",
});
const leagueSpartan = localFont({
	src: "./fonts/LeagueSpartan.woff",
	variable: "--font-leagueSpartan",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${lemon.variable} antialiased ${lexend.variable} ${lexendDeca.variable} ${lexendExa.variable} ${leagueSpartan.variable} `}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="light"
					enableSystem
					disableTransitionOnChange
				>
					<Navbar />
					<Toaster />
					<Main />
					{children}
					<Footer />
				</ThemeProvider>
			</body>
		</html>
	);
}
